name: "Nuclei Build Security"
description: "Nuclei Scanner with upload to CVEDB build Security"
author: "CVEDB"
inputs:
  nuclei_key:
    description: "Nuclei Provided by CSPM"
    required: true
    
    
    
runs:
  using: "docker"
  image: "Dockerfile"
    
