name: build
on:
  push:
    branches:
      - main
      - master
  pull_request:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run nuclei Build Security
        uses: CVEDB/nuclei-scan@main
        with:
          github_secret: ${ secret.GITHUB_SECRET }
